// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwjCiMW1dqkTHxSDPfXLN4jWSx1dq40ec',
    appId: '1:327802165543:web:853002dd159fd079ea7102',
    messagingSenderId: '327802165543',
    projectId: 'flutter-web-sample-1b409',
    authDomain: 'flutter-web-sample-1b409.firebaseapp.com',
    storageBucket: 'flutter-web-sample-1b409.appspot.com',
    measurementId: 'G-ZL7PZMZY9T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWBxcVQLe0p5egvsTM9SzjXnrlVvyOrdo',
    appId: '1:327802165543:android:3fae821ebde9ae3eea7102',
    messagingSenderId: '327802165543',
    projectId: 'flutter-web-sample-1b409',
    storageBucket: 'flutter-web-sample-1b409.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmpykue3yIhWZ3Cim2jnYgg1z2Df2re1M',
    appId: '1:327802165543:ios:0b6f094ae9686016ea7102',
    messagingSenderId: '327802165543',
    projectId: 'flutter-web-sample-1b409',
    storageBucket: 'flutter-web-sample-1b409.appspot.com',
    iosBundleId: 'com.example.flutterWebSample',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCmpykue3yIhWZ3Cim2jnYgg1z2Df2re1M',
    appId: '1:327802165543:ios:b28610102b7882daea7102',
    messagingSenderId: '327802165543',
    projectId: 'flutter-web-sample-1b409',
    storageBucket: 'flutter-web-sample-1b409.appspot.com',
    iosBundleId: 'com.example.flutterWebSample.RunnerTests',
  );
}
